# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes libgsl0-dev
  - sudo apt-get install -y --force-yes libgsl0ldbl
env: 
  PKG_LIBS=-L/usr/local/opt/gettext/lib
  CFLAGS=-I/usr/local/opt/gsl/include
  LDFLAGS=-L/usr/local/opt/gsl/lib -lgsl -lgslcblas
