# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - setuid root apt-get -qq update
  - setuid root apt-get install -y --force-yes libgsl0ldbl
